server.port=8080
# vscode console highlight
spring.output.ansi.enabled=always
# utf-8
server.servlet.encoding.charset=utf-8
server.servlet.encoding.force=true
# DB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
# JPA table create or none
spring.jpa.hibernate.ddl-auto=create
# query log
spring.jpa.show-sql=true
# dummy data
spring.sql.init.data-locations=classpath:db/data.sql
# create dummy data  after ddl-auto create
spring.jpa.defer-datasource-initialization=true
# sql formatter
spring.jpa.properties.hibernate.format_sql=true
# log
logging.level.org.example.jjava_main=DEBUG
logging.level.org.hibernate.type=TRACE

# Redis host (cloud)
spring.data.redis.host=redis-10960.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com

# Redis port
spring.data.redis.port=10960

# Redis password
spring.data.redis.password=qwFHtgwZjiCjUo3CzgQ2jdoQpODn7FGP

# set redis to server session
spring.session.store-type=redis

# session timeout
server.servlet.session.timeout=1800s